apiVersion: apps/v1
kind: Deployment
metadata:
  name: "deployment-on-app-node"
spec:
  replicas: 2
  selector:
    matchLabels:
      node-role.kubernetes.io: "app"
  template:
    metadata:
      labels:
        node-role.kubernetes.io: "app"
    spec:
      nodeSelector:
        node-role.kubernetes.io: "app"
      containers:
        - name: "deployment-on-app-node"
          image: alpine
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c", "while true; do echo $(date); done" ]
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m